apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: skumarsahdevopsdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skumarsahdevopsdemo 
    spec:
      containers:
        - name: skumarsahdevopsdemo 
          image: k8devreg.azurecr.io/skumarsahdevopsdemo
          ports:
          - containerPort: 8080